use std::str::FromStr;

use cedar_policy::PolicySet;

use crate::dsl::{DslEffect, DslPolicy};
use crate::error::PolicyError;

/// Translate DSL policies into a Cedar policy document string.
pub fn dsl_to_cedar(policies: &[DslPolicy]) -> Result<String, PolicyError> {
    let mut out = String::new();
    out.push_str("// Generated by authz-policy from PAAC DSL\n");
    for p in policies {
        out.push_str(&translate_one(p)?);
        out.push('\n');
    }
    Ok(out)
}

pub fn cedar_policy_set_from_dsl(policies: &[DslPolicy]) -> Result<PolicySet, PolicyError> {
    let cedar = dsl_to_cedar(policies)?;
    PolicySet::from_str(&cedar).map_err(|e| PolicyError::Cedar(e.to_string()))
}

fn translate_one(p: &DslPolicy) -> Result<String, PolicyError> {
    let effect = match p.effect {
        DslEffect::Allow => "permit",
        DslEffect::Deny | DslEffect::Review => "forbid", // REVIEW treated as forbid for MVP eval; gateway can flag
    };

    let mut when_parts: Vec<String> = Vec::new();
    when_parts.push(format!(
        "context.resource_kind == \"{}\"",
        p.resource
    ));
    when_parts.push(format!(
        "context.action_name == \"{}\"",
        p.action
    ));

    if !p.when_roles.is_empty() {
        let role_checks = p
            .when_roles
            .iter()
            .map(|r| format!("context.principal_roles.contains(\"{r}\")"))
            .collect::<Vec<_>>()
            .join(" || ");
        when_parts.push(format!("({role_checks})"));
    }

    // subject constraints for allow
    if !p.where_subjects.is_empty() {
        let mut subj = Vec::new();
        for s in &p.where_subjects {
            match s.as_str() {
                "SELF" => subj.push("context.subject_is_self".to_string()),
                "DIRECT_REPORTS" => subj.push("context.subject_in_direct_reports".to_string()),
                other => subj.push(format!("context.subject_id == \"{other}\"")),
            }
        }
        when_parts.push(format!("({})", subj.join(" || ")));
    }

    if !p.where_subject_groups.is_empty() {
        let gchecks = p
            .where_subject_groups
            .iter()
            .map(|g| format!("context.subject_groups.contains(\"{g}\")"))
            .collect::<Vec<_>>()
            .join(" || ");
        when_parts.push(format!("({gchecks})"));
    }

    if !p.unless_roles.is_empty() {
        let unless = p
            .unless_roles
            .iter()
            .map(|r| format!("context.principal_roles.contains(\"{r}\")"))
            .collect::<Vec<_>>()
            .join(" || ");
        when_parts.push(format!("!({unless})"));
    }

    // salary_export style: deny EXPORT SALARY unless PAYROLL_ADMIN — no when_roles
    // already handled via unless

    let when = when_parts.join(" &&\n  ");

    Ok(format!(
        r#"@id("{id}")
{effect} (
  principal,
  action == Action::"{action}",
  resource
) when {{
  {when}
}};
"#,
        id = p.id,
        effect = effect,
        action = p.action,
        when = when
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dsl::parse_dsl;

    #[test]
    fn translates_and_parses_cedar() {
        let src = include_str!("../../../examples/policies/hr_travel.dsl");
        let policies = parse_dsl(src).unwrap();
        let set = cedar_policy_set_from_dsl(&policies).unwrap();
        assert!(!set.is_empty());
    }
}
